[versions]
# Plugins
worldedit = "7.2.14"
protocollib = "5.0.0-SNAPSHOT"

# Third party
bstats = "3.0.0"

# Gradle plugins
shadow = "8.1.1"
spotless = "6.17.0"
bukkityml = "0.5.3"

[libraries]
# Plugins
worldedit = { group = "com.sk89q.worldedit", name = "worldedit-bukkit", version.ref = "worldedit" }
protocollib = { group = "com.comphenix.protocol", name = "ProtocolLib", version.ref = "protocollib" }

[plugins]
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
pluginyml = { id = "net.minecrell.plugin-yml.bukkit", version.ref = "bukkityml" }
