name: Announce release on discord
on:
  release:
    types: [published]
jobs:
  send_announcement:
    runs-on: ubuntu-latest
    steps:
      - name: send custom message with args
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USERNAME: PlotHider Release
        uses: Ilshidur/action-discord@0.3.2
        with:
          args: |
            "<@&673138796690276352>"
            ""
            "<:plothider:730750385177886820> **PlotHider ${{ github.event.release.tag_name }} has been released!**"
            ""
            "Click here to view changelog: https://github.com/IntellectualSites/plothider/releases/tag/${{ github.event.release.tag_name }}"
            ""
            "The download is available at:"
            "- Spigot: <https://www.spigotmc.org/resources/20701/>"
